apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hamza5245/wanderlust_backend:28
        ports:
        - containerPort: 8002
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/wanderlust"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8002
      targetPort: 8002
